version: "3.6"
services:
  frontend:
    container_name: svelte_app
    image: teal-frontend_frontend
    build: .
    command: sh -c "npm run dev"  # comment out before installing svelte
    # command: echo 'ready'
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    network_mode: "host"
